services:
  openresty:
    build: .
    ports:
      - '8080:80'
    volumes:
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './http.js:/usr/local/openresty/nginx/conf/http.js'
