load_module /usr/local/openresty/nginx/modules/ngx_otel_module.so;
events {}
http {
    otel_exporter {
        endpoint localhost:4317;
    }
    otel_trace on;
    server {
        listen 80;
        location / {
            return 200 'Hello, World!';
        }
    }
}
